Not destructuring so that can handle null values
 error Building static HTML failed for path "/work-days/untitled-entry-2023-01-21-at-18-37-28/"

  15 |   const siteTitle = data.site.siteMetadata?.title || `Title`;
  16 |   const *** previous, next *** = data;
> 17 |   const *** meetingPointWhatThreeWords, meetingPointDescription *** =
     |           ^
  18 |     parseMeetingPoint(post.meetingPointWhat3words);
  19 |
  20 |   return (

  WebpackError: TypeError: Cannot destructure property 'meetingPointWhatThreeWor  ds' of 'parseMeetingPoint(...)' as it is null.